# -*- coding: utf-8 -*-
"""convertir_json_to_xml.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JbIt6Jhnd5i9uz3Lv1nEjY83e5gIdlVC
"""

!pip install json2xml

import os
import json
from json2xml import json2xml
from json2xml.utils import readfromjson, readfromstring

def json_to_xml(input_file, output_file):
    with open(input_file, 'r') as json_file:
        data = json.load(json_file)

    xml_data = json2xml.Json2xml(data).to_xml()

    with open(output_file, 'w') as xml_file:
        xml_file.write(xml_data)

def convert_files_in_folder(input_folder, output_folder):
    if not os.path.exists(output_folder):
        os.makedirs(output_folder)

    for filename in os.listdir(input_folder):
        if filename.endswith(".json"):
            input_file_path = os.path.join(input_folder, filename)
            output_file_path = os.path.join(output_folder, filename.replace(".json", ".xml"))
            json_to_xml(input_file_path, output_file_path)
            print(f"Converted {input_file_path} to {output_file_path}")

if __name__ == "__main__":
    input_folder = "/content/drive/MyDrive/Anotaciones"  # Reemplaza con la carpeta que contiene los archivos .json
    output_folder = "/content/drive/MyDrive/anotaciones-xml"  # Reemplaza con la carpeta donde guardarás los archivos .xml
    convert_files_in_folder(input_folder, output_folder)