# -*- coding: utf-8 -*-
"""separador_xml_jpg.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ijeac9tkSpw3pSB4z_gJbabV8uPovhAJ
"""

import os
import shutil

# Ruta de la carpeta principal donde se encuentran los archivos
folder_path = "/content/drive/MyDrive/datos"

# Rutas de las carpetas de destino para los archivos .xml y .jpg
annotations_folder = "/content/drive/MyDrive/Anotaciones/"
images_folder = "/content/drive/MyDrive/Imagenes/"

# Crea las carpetas de destino si no existen
os.makedirs(annotations_folder, exist_ok=True)
os.makedirs(images_folder, exist_ok=True)

# Recorre todos los archivos en la carpeta principal
for file_name in os.listdir(folder_path):
    # Ruta completa del archivo
    file_path = os.path.join(folder_path, file_name)

    # Verifica si es un archivo .xml
    if file_name.lower().endswith(".xml"):
        # Mueve el archivo a la carpeta de anotaciones
        shutil.move(file_path, os.path.join(annotations_folder, file_name))

    # Verifica si es un archivo .jpg
    elif file_name.lower().endswith(".jpg"):
        # Mueve el archivo a la carpeta de imágenes
        shutil.move(file_path, os.path.join(images_folder, file_name))